### ISSUE TITLE
v2.0.0 Tracking

### ISSUE THREAD

**Issue by tizz98** [noteable-io/magicbell-python-sdk#9]
Laundry list of tasks and/or features to be completed for the v2.0.0 release of this SDK.

- [ ] Rename `GraphQLAPI::query` to `GraphQLAPI::execute`
- [ ] Use `gql` library for better graphql support (https://pypi.org/project/gql/ & https://gql.readthedocs.io/en/latest/async/async_usage.html#async-usage)
- [ ] Auto-generate library from open api specification
- [ ] Ensure all public APIs are implemented (https://www.magicbell.com/docs/rest-api/reference)
